/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/wheelhouse/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_wheelhouse_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_api_wheelhouse_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_wheelhouse_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_wheelhouse_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/market-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Context */
        get: operations["market_context_api_wheelhouse_v1_market_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_wheelhouse_v1_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshots */
        get: operations["snapshots_api_wheelhouse_v1_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_wheelhouse_v1_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch */
        get: operations["batch_api_wheelhouse_v1_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule */
        post: operations["schedule_api_wheelhouse_v1_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage */
        get: operations["storage_api_wheelhouse_v1_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connection */
        get: operations["connection_api_wheelhouse_v1_portfolio_connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_wheelhouse_v1_portfolio_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover */
        post: operations["discover_api_wheelhouse_v1_portfolio_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_wheelhouse_v1_portfolio_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/sync-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Job */
        get: operations["sync_job_api_wheelhouse_v1_portfolio_sync_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_wheelhouse_v1_portfolio_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo */
        post: operations["demo_api_wheelhouse_v1_portfolio_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_wheelhouse_v1_portfolio_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cycle */
        post: operations["cycle_api_wheelhouse_v1_portfolio_cycles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Event */
        post: operations["event_api_wheelhouse_v1_portfolio_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Annotation */
        post: operations["annotation_api_wheelhouse_v1_portfolio_annotations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/fee-corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fee Correction */
        post: operations["fee_correction_api_wheelhouse_v1_portfolio_fee_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wheelhouse/v1/portfolio/reconcile-fill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile */
        post: operations["reconcile_api_wheelhouse_v1_portfolio_reconcile_fill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Analysis */
        Analysis: {
            /** Snapshot Id */
            snapshot_id: string;
            /** Input Hash */
            input_hash: string;
            stream: components["schemas"]["Stream-Output"];
            rules: components["schemas"]["Rules-Output"];
            /**
             * Market At
             * Format: date-time
             */
            market_at: string;
            /**
             * Knowledge At
             * Format: date-time
             */
            knowledge_at: string;
            /** Fetched At */
            fetched_at: string | null;
            /** Closed Bar Time */
            closed_bar_time: string | null;
            /** Forming Bar Time */
            forming_bar_time: string | null;
            /** Expected Next Close */
            expected_next_close: string | null;
            /**
             * Data State
             * @enum {string}
             */
            data_state: "fresh" | "delayed" | "stale" | "unavailable" | "simulated";
            /**
             * Mode
             * @enum {string}
             */
            mode: "as_known" | "retrospective";
            /** Warmup Required */
            warmup_required: number;
            /** Warmup Complete */
            warmup_complete: boolean;
            /** Issues */
            issues: string[];
            /** Bars */
            bars: components["schemas"]["StoredBar"][];
            /** Points */
            points: components["schemas"]["Point"][];
            /**
             * Signal Status
             * @default not_implemented
             * @constant
             */
            signal_status: "not_implemented";
            demark: components["schemas"]["DemarkResult"] | null;
        };
        /** Annotation */
        Annotation: {
            /**
             * Source
             * @enum {string}
             */
            source: "demo" | "moomoo";
            /** Account Id */
            account_id: string;
            /** Author */
            author: string;
            /** Reason */
            reason: string;
            instrument?: components["schemas"]["Instrument-Input"] | null;
            quote?: components["schemas"]["Quote-Input"] | null;
            fx?: components["schemas"]["FxRate"] | null;
        };
        /** Bar */
        Bar: {
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /**
             * Close Time
             * Format: date-time
             */
            close_time: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Volume */
            volume: string | null;
            /** Is Closed */
            is_closed: boolean;
        };
        /** BarRef */
        BarRef: {
            /** Revision Id */
            revision_id: string;
            /**
             * Open Time
             * Format: date-time
             */
            open_time: string;
            /**
             * Close Time
             * Format: date-time
             */
            close_time: string;
            /** Close */
            close: string;
        };
        /** Batch */
        Batch: {
            stream: components["schemas"]["Stream-Output"];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Bars */
            bars: components["schemas"]["Bar"][];
            /** Raw Payload */
            raw_payload: {
                [key: string]: unknown;
            };
        };
        /** Cycle */
        Cycle: {
            /** Cycle Id */
            cycle_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "demo" | "moomoo";
            /** Account Id */
            account_id: string;
            /** Underlying */
            underlying: string;
            /** Currency */
            currency: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CycleResult */
        CycleResult: {
            cycle: components["schemas"]["Cycle"];
            /**
             * Method
             * @default FIFO; option premiums realized separately; assignment shares at strike
             */
            method: string;
            /**
             * State
             * @enum {string}
             */
            state: "empty" | "open" | "closed" | "incomplete";
            /** Premium Received */
            premium_received: string | null;
            /** Premium Paid */
            premium_paid: string | null;
            /** Gross Cash Movement */
            gross_cash_movement: string | null;
            /** Known Fees */
            known_fees: string;
            /** Net Cash Movement */
            net_cash_movement: string | null;
            /** Realized Gross */
            realized_gross: string | null;
            /** Realized Net */
            realized_net: string | null;
            /** Unrealized */
            unrealized: string | null;
            /** Lots */
            lots: components["schemas"]["Lot"][];
            /** Events */
            events: components["schemas"]["LedgerEvent-Output"][];
            /** Issues */
            issues: string[];
        };
        /** DemarkConfig */
        "DemarkConfig-Input": {
            /**
             * Variant
             * @default sequential
             * @constant
             */
            variant: "sequential";
            /**
             * Ruleset Version
             * @default wheelhouse-sequential-1
             * @enum {string}
             */
            ruleset_version: "wheelhouse-sequential-1" | "wheelhouse-sequential-2";
            /**
             * Price Flip Required
             * @default true
             */
            price_flip_required: boolean;
            /**
             * Perfection Policy
             * @default strict
             * @enum {string}
             */
            perfection_policy: "strict" | "strict_at_nine";
            /**
             * Same Side Policy
             * @default parallel
             * @enum {string}
             */
            same_side_policy: "parallel" | "retain_active";
            /**
             * Qualifier 8 Vs 5
             * @default false
             * @constant
             */
            qualifier_8_vs_5: false;
            /**
             * Risk Formula
             * @default countdown_span_true_extreme_earliest
             * @constant
             */
            risk_formula: "countdown_span_true_extreme_earliest";
            /**
             * Tdst Breach
             * @default true_extreme
             * @enum {string}
             */
            tdst_breach: "true_extreme" | "close";
            /**
             * Risk Breach
             * @default close
             * @enum {string}
             */
            risk_breach: "close" | "true_extreme";
            /**
             * Recycling
             * @default range_and_22
             * @enum {string}
             */
            recycling: "range_and_22" | "none";
            /** Validity Bars */
            validity_bars?: number | null;
        };
        /** DemarkConfig */
        "DemarkConfig-Output": {
            /**
             * Variant
             * @default sequential
             * @constant
             */
            variant: "sequential";
            /**
             * Ruleset Version
             * @default wheelhouse-sequential-1
             * @enum {string}
             */
            ruleset_version: "wheelhouse-sequential-1" | "wheelhouse-sequential-2";
            /**
             * Price Flip Required
             * @default true
             */
            price_flip_required: boolean;
            /**
             * Perfection Policy
             * @default strict
             * @enum {string}
             */
            perfection_policy: "strict" | "strict_at_nine";
            /**
             * Same Side Policy
             * @default parallel
             * @enum {string}
             */
            same_side_policy: "parallel" | "retain_active";
            /**
             * Qualifier 8 Vs 5
             * @default false
             * @constant
             */
            qualifier_8_vs_5: false;
            /**
             * Risk Formula
             * @default countdown_span_true_extreme_earliest
             * @constant
             */
            risk_formula: "countdown_span_true_extreme_earliest";
            /**
             * Tdst Breach
             * @default true_extreme
             * @enum {string}
             */
            tdst_breach: "true_extreme" | "close";
            /**
             * Risk Breach
             * @default close
             * @enum {string}
             */
            risk_breach: "close" | "true_extreme";
            /**
             * Recycling
             * @default range_and_22
             * @enum {string}
             */
            recycling: "range_and_22" | "none";
            /** Validity Bars */
            validity_bars: number | null;
        };
        /** DemarkEvent */
        DemarkEvent: {
            /** Sequence Id */
            sequence_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Kind
             * @enum {string}
             */
            kind: "setup_count" | "setup_completed" | "setup_interrupted" | "perfected" | "countdown_count" | "deferred13" | "qualified13" | "cancelled" | "recycled" | "invalidated" | "expired" | "continuity_lost";
            bar: components["schemas"]["BarRef"];
            /** Count */
            count: number | null;
            /** Reason */
            reason: string;
        };
        /** DemarkResult */
        DemarkResult: {
            config: components["schemas"]["DemarkConfig-Output"];
            /** Input Hash */
            input_hash: string;
            /** History Start */
            history_start: string | null;
            /** History End */
            history_end: string | null;
            /**
             * History Status
             * @enum {string}
             */
            history_status: "window_only" | "gapped" | "empty";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "warming_up" | "unavailable";
            /**
             * Warmup Required
             * @default 6
             */
            warmup_required: number;
            /** Sequences */
            sequences: components["schemas"]["DemarkSequence"][];
            /** Events */
            events: components["schemas"]["DemarkEvent"][];
            /** Qualified13 Count */
            qualified13_count: number;
            /** Issues */
            issues: string[];
        };
        /** DemarkSequence */
        DemarkSequence: {
            /** Sequence Id */
            sequence_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Setup Count */
            setup_count: number;
            /**
             * Setup Status
             * @enum {string}
             */
            setup_status: "forming" | "completed" | "interrupted";
            /** Setup Bars */
            setup_bars: components["schemas"]["BarRef"][];
            /** Setup Perfected */
            setup_perfected: boolean | null;
            /** Perfected At */
            perfected_at: string | null;
            /**
             * Countdown Count
             * @default 0
             */
            countdown_count: number;
            /**
             * Countdown Status
             * @default inactive
             * @enum {string}
             */
            countdown_status: "inactive" | "active" | "count13_unqualified" | "qualified13" | "cancelled" | "recycled";
            /** Countdown Bars */
            countdown_bars: components["schemas"]["BarRef"][];
            countdown_bar8: components["schemas"]["BarRef"] | null;
            /** Qualification Threshold */
            qualification_threshold: string | null;
            /** Qualified At */
            qualified_at: string | null;
            /** Confirmation Close */
            confirmation_close: string | null;
            /** Tdst */
            tdst: string | null;
            tdst_source: components["schemas"]["BarRef"] | null;
            /** Tdst Breached At */
            tdst_breached_at: string | null;
            /** Risk Level */
            risk_level: string | null;
            risk_source: components["schemas"]["BarRef"] | null;
            /**
             * Risk Status
             * @default not_available
             * @enum {string}
             */
            risk_status: "not_available" | "valid" | "invalidated" | "expired" | "unknown";
            /** Risk Ended At */
            risk_ended_at: string | null;
            /**
             * Continuity
             * @default observed
             * @enum {string}
             */
            continuity: "observed" | "lost";
            /** Bars Since Setup9 */
            bars_since_setup9: number | null;
            /** Bars Since Qualified13 */
            bars_since_qualified13: number | null;
            /** Elapsed Since Setup9 Seconds */
            elapsed_since_setup9_seconds: number | null;
            /** Elapsed Since Qualified13 Seconds */
            elapsed_since_qualified13_seconds: number | null;
            /** Next Conditions */
            next_conditions: components["schemas"]["NextCondition"][];
        };
        /** DemarkSummary */
        DemarkSummary: {
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Trend
             * @enum {string}
             */
            trend: "up" | "down";
            /**
             * Phase
             * @enum {string}
             */
            phase: "setup" | "countdown";
            /** Step */
            step: number;
            /**
             * Target
             * @enum {integer}
             */
            target: 9 | 13;
            /** Setup Step */
            setup_step: number;
            /** Countdown Step */
            countdown_step: number;
            /** Rounds */
            rounds: components["schemas"]["Round"][];
            last_signal: components["schemas"]["SignalRef"] | null;
            prev: components["schemas"]["PrevCountdown"] | null;
            second: components["schemas"]["SecondSetup"] | null;
            /** Bars Since Qualified13 */
            bars_since_qualified13: number | null;
            setup_run: components["schemas"]["SetupRun"];
            risk: components["schemas"]["SummaryRisk"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Close */
            close: string;
        };
        /** Exposure */
        Exposure: {
            /** Underlying */
            underlying: string;
            /** Currency */
            currency: string;
            /** Share Delta */
            share_delta: string | null;
            /** Share Gamma */
            share_gamma: string | null;
            /** Theta Daily */
            theta_daily: string | null;
            /** Vega Point */
            vega_point: string | null;
            /** Dollar Delta Base */
            dollar_delta_base: string | null;
            /** Issues */
            issues: string[];
        };
        /** FeeCorrection */
        FeeCorrection: {
            /** Event Id */
            event_id: string;
            /** Fee */
            fee: string;
            /** Author */
            author: string;
            /** Reason */
            reason: string;
        };
        /** FillReconciliation */
        FillReconciliation: {
            /** Event Id */
            event_id: string;
            /** Record Id */
            record_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Fee */
            fee?: string | null;
            /** Author */
            author: string;
            /** Reason */
            reason: string;
        };
        /** FxRate */
        FxRate: {
            /** Currency */
            currency: string;
            /** To Base */
            to_base: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Source */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Instrument */
        "Instrument-Input": {
            /** Code */
            code: string;
            /** Underlying */
            underlying: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "stock" | "call" | "put";
            /** Currency */
            currency: string;
            /** Multiplier */
            multiplier: string;
            /** Strike */
            strike?: string | null;
            /** Expiry */
            expiry?: string | null;
            /** Source */
            source: string;
        };
        /** Instrument */
        "Instrument-Output": {
            /** Code */
            code: string;
            /** Underlying */
            underlying: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "stock" | "call" | "put";
            /** Currency */
            currency: string;
            /** Multiplier */
            multiplier: string;
            /** Strike */
            strike: string | null;
            /** Expiry */
            expiry: string | null;
            /** Source */
            source: string;
        };
        /** Integrations */
        Integrations: {
            /**
             * Broker
             * @constant
             */
            broker: "not_connected";
            /**
             * Market Data
             * @enum {string}
             */
            market_data: "not_connected" | "available";
            /**
             * Analytics
             * @constant
             */
            analytics: "baseline_ready";
        };
        /** Job */
        Job: {
            /** Job Id */
            job_id: string;
            request: components["schemas"]["JobRequest-Output"];
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "retry_wait" | "succeeded" | "failed";
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Lease Until */
            lease_until: string | null;
            /** Checkpoint Batch Id */
            checkpoint_batch_id: string | null;
            /** Snapshot Id */
            snapshot_id: string | null;
            /** Error Code */
            error_code: string | null;
        };
        /** JobEvent */
        JobEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** State */
            state: string;
            /** Reason */
            reason: string;
        };
        /** JobRequest */
        "JobRequest-Input": {
            /**
             * Kind
             * @default refresh
             * @enum {string}
             */
            kind: "refresh" | "analyze";
            stream: components["schemas"]["Stream-Input"];
            rules?: components["schemas"]["Rules-Input"];
            /** Market At */
            market_at?: string | null;
            /** Knowledge At */
            knowledge_at?: string | null;
        };
        /** JobRequest */
        "JobRequest-Output": {
            /**
             * Kind
             * @default refresh
             * @enum {string}
             */
            kind: "refresh" | "analyze";
            stream: components["schemas"]["Stream-Output"];
            rules: components["schemas"]["Rules-Output"];
            /** Market At */
            market_at: string | null;
            /** Knowledge At */
            knowledge_at: string | null;
        };
        /** LedgerEvent */
        "LedgerEvent-Input": {
            /** Event Id */
            event_id: string;
            /** Cycle Id */
            cycle_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "buy_open" | "sell_open" | "buy_close" | "sell_close" | "expire" | "assign" | "exercise" | "cash_settle";
            instrument: components["schemas"]["Instrument-Input"];
            /** Quantity */
            quantity: string;
            /** Price */
            price: string;
            /** Fee */
            fee?: string | null;
            /** Source Record Id */
            source_record_id?: string | null;
            /** Settlement Record Id */
            settlement_record_id?: string | null;
            /** Roll Group */
            roll_group?: string | null;
            /** Evidence Issues */
            evidence_issues?: string[];
            /** Author */
            author: string;
            /** Reason */
            reason: string;
        };
        /** LedgerEvent */
        "LedgerEvent-Output": {
            /** Event Id */
            event_id: string;
            /** Cycle Id */
            cycle_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "buy_open" | "sell_open" | "buy_close" | "sell_close" | "expire" | "assign" | "exercise" | "cash_settle";
            instrument: components["schemas"]["Instrument-Output"];
            /** Quantity */
            quantity: string;
            /** Price */
            price: string;
            /** Fee */
            fee: string | null;
            /** Source Record Id */
            source_record_id: string | null;
            /** Settlement Record Id */
            settlement_record_id: string | null;
            /** Roll Group */
            roll_group: string | null;
            /** Evidence Issues */
            evidence_issues: string[];
            /** Author */
            author: string;
            /** Reason */
            reason: string;
        };
        /** Lot */
        Lot: {
            /** Code */
            code: string;
            /** Quantity */
            quantity: string;
            /** Entry Price */
            entry_price: string;
            /** Opening Event Id */
            opening_event_id: string;
        };
        /** MarketContext */
        MarketContext: {
            /**
             * Source
             * @enum {string}
             */
            source: "fixture" | "binance";
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "BTCUSDT" | "ETHUSDT";
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Market At
             * Format: date-time
             */
            market_at: string;
            /**
             * Knowledge At
             * Format: date-time
             */
            knowledge_at: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "as_known" | "retrospective";
            config: components["schemas"]["DemarkConfig-Output"];
            /** Window */
            window: number;
            /** Timeframes */
            timeframes: components["schemas"]["TimeframeContext"][];
            intraday: components["schemas"]["RegimeState"];
            swing: components["schemas"]["RegimeState"];
        };
        /** NewCycle */
        NewCycle: {
            /**
             * Source
             * @enum {string}
             */
            source: "demo" | "moomoo";
            /** Account Id */
            account_id: string;
            /** Underlying */
            underlying: string;
            /** Currency */
            currency: string;
            /** Name */
            name: string;
        };
        /** NewTrend */
        NewTrend: {
            /** Present */
            present: boolean;
            /**
             * Trend
             * @enum {string}
             */
            trend: "up" | "down";
            /** Step */
            step: number;
            /** Confirmed */
            confirmed: boolean;
            /** Seconds */
            seconds: number | null;
        };
        /** NextBarNeeds */
        NextBarNeeds: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "above" | "below";
            /** Price */
            price: string;
        };
        /** NextCondition */
        NextCondition: {
            /**
             * Field
             * @enum {string}
             */
            field: "close" | "low" | "high";
            /**
             * Operator
             * @enum {string}
             */
            operator: "<" | ">" | "<=" | ">=";
            /** Threshold */
            threshold: string;
            reference: components["schemas"]["BarRef"];
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "setup" | "countdown" | "qualification13";
        };
        /** Point */
        Point: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Revision Id */
            revision_id: string;
            /** Sma */
            sma: string | null;
            /** Prior High */
            prior_high: string | null;
            /** Prior Low */
            prior_low: string | null;
        };
        /** PortfolioCapture */
        PortfolioCapture: {
            /**
             * Source
             * @enum {string}
             */
            source: "demo" | "moomoo";
            /** Account Id */
            account_id: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Snapshot Observed At */
            snapshot_observed_at: string | null;
            /**
             * Base Currency
             * @default USD
             */
            base_currency: string;
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** Instruments */
            instruments: components["schemas"]["Instrument-Output"][];
            /** Quotes */
            quotes: components["schemas"]["Quote-Output"][];
            /** Fx */
            fx: components["schemas"]["FxRate"][];
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
            /** Errors */
            errors: {
                [key: string]: string;
            };
            /** History Start */
            history_start: string | null;
            /** History End */
            history_end: string | null;
        };
        /** PortfolioWorkspace */
        PortfolioWorkspace: {
            capture: components["schemas"]["PortfolioCapture"] | null;
            /** Cycles */
            cycles: components["schemas"]["CycleResult"][];
            risk: components["schemas"]["RiskResult"] | null;
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
            /** Audit */
            audit: {
                [key: string]: unknown;
            }[];
            /**
             * State
             * @enum {string}
             */
            state: "available" | "stale" | "unavailable" | "simulated";
            /** Issues */
            issues: string[];
        };
        /** Position */
        Position: {
            /** Code */
            code: string;
            /** Quantity */
            quantity: string;
            /** Mark */
            mark: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** PrevCountdown */
        PrevCountdown: {
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Countdown */
            countdown: number;
            /** Qualified */
            qualified: boolean;
            /** Bars Ago */
            bars_ago: number;
        };
        /** Quote */
        "Quote-Input": {
            /** Code */
            code: string;
            /** Spot */
            spot: string;
            /** Delta */
            delta?: string | null;
            /** Gamma */
            gamma?: string | null;
            /** Theta */
            theta?: string | null;
            /** Vega */
            vega?: string | null;
            /**
             * Units
             * @enum {string}
             */
            units: "per_share" | "per_contract";
            /**
             * Theta Basis
             * @enum {string}
             */
            theta_basis: "day" | "year";
            /**
             * Vega Basis
             * @enum {string}
             */
            vega_basis: "percentage_point" | "unit_volatility";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Source */
            source: string;
        };
        /** Quote */
        "Quote-Output": {
            /** Code */
            code: string;
            /** Spot */
            spot: string;
            /** Delta */
            delta: string | null;
            /** Gamma */
            gamma: string | null;
            /** Theta */
            theta: string | null;
            /** Vega */
            vega: string | null;
            /**
             * Units
             * @enum {string}
             */
            units: "per_share" | "per_contract";
            /**
             * Theta Basis
             * @enum {string}
             */
            theta_basis: "day" | "year";
            /**
             * Vega Basis
             * @enum {string}
             */
            vega_basis: "percentage_point" | "unit_volatility";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Source */
            source: string;
        };
        /** RegimeState */
        RegimeState: {
            /**
             * Anchor
             * @enum {string}
             */
            anchor: "5m" | "15m" | "1h" | "4h" | "1d";
            /**
             * Value
             * @enum {string}
             */
            value: "decay" | "rev" | "pump" | "none" | "unavailable";
        };
        /** RiskResult */
        RiskResult: {
            /** Base Currency */
            base_currency: string;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "partial" | "unavailable";
            /** Exposures */
            exposures: components["schemas"]["Exposure"][];
            /** Dollar Delta */
            dollar_delta: string | null;
            /** Theta Daily */
            theta_daily: string | null;
            /** Vega Point */
            vega_point: string | null;
            /** Issues */
            issues: string[];
        };
        /** Round */
        Round: {
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Trend
             * @enum {string}
             */
            trend: "up" | "down";
            /** Setup */
            setup: number;
            /** Countdown */
            countdown: number;
            /** Setup9 At */
            setup9_at: string | null;
            /** Qualified13 At */
            qualified13_at: string | null;
        };
        /** Rules */
        "Rules-Input": {
            /**
             * Engine Version
             * @default baseline-v1
             * @constant
             */
            engine_version: "baseline-v1";
            /**
             * Window
             * @default 20
             */
            window: number;
            demark?: components["schemas"]["DemarkConfig-Input"] | null;
        };
        /** Rules */
        "Rules-Output": {
            /**
             * Engine Version
             * @default baseline-v1
             * @constant
             */
            engine_version: "baseline-v1";
            /**
             * Window
             * @default 20
             */
            window: number;
            demark: components["schemas"]["DemarkConfig-Output"] | null;
        };
        /** Schedule */
        Schedule: {
            /** Schedule Id */
            schedule_id: string;
            request: components["schemas"]["ScheduleRequest-Output"];
            /**
             * Next Due
             * Format: date-time
             */
            next_due: string;
        };
        /** ScheduleRequest */
        "ScheduleRequest-Input": {
            stream: components["schemas"]["Stream-Input"];
            rules?: components["schemas"]["Rules-Input"];
            /** Enabled */
            enabled: boolean;
        };
        /** ScheduleRequest */
        "ScheduleRequest-Output": {
            stream: components["schemas"]["Stream-Output"];
            rules: components["schemas"]["Rules-Output"];
            /** Enabled */
            enabled: boolean;
        };
        /** SecondSetup */
        SecondSetup: {
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Trend
             * @enum {string}
             */
            trend: "up" | "down";
            /** Step */
            step: number;
            /** Setup9 At */
            setup9_at: string | null;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /**
             * Service
             * @constant
             */
            service: "wheelhouse-python";
            /**
             * Status
             * @constant
             */
            status: "ready";
            /**
             * Contract Version
             * @constant
             */
            contract_version: "1";
            /** Service Version */
            service_version: string;
            /** Python Version */
            python_version: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Read Only
             * @constant
             */
            read_only: true;
            integrations: components["schemas"]["Integrations"];
            /** Capabilities */
            capabilities: string[];
        };
        /** SetupRun */
        SetupRun: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Count */
            count: number;
            /** Active */
            active: boolean;
            /** Completed */
            completed: boolean;
        };
        /** Signal */
        Signal: {
            /**
             * N
             * @enum {integer}
             */
            n: 1 | 2;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Active */
            active: boolean;
            /** Price */
            price: string | null;
            /** Base Level */
            base_level: number | null;
            /** Intraday Level */
            intraday_level: number | null;
            /** Swing Level */
            swing_level: number | null;
        };
        /** SignalRef */
        SignalRef: {
            /**
             * Kind
             * @enum {integer}
             */
            kind: 9 | 13;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
        };
        /** SnapshotSummary */
        SnapshotSummary: {
            /** Snapshot Id */
            snapshot_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Market At
             * Format: date-time
             */
            market_at: string;
            /**
             * Knowledge At
             * Format: date-time
             */
            knowledge_at: string;
            rules: components["schemas"]["Rules-Output"];
            /** Data State */
            data_state: string;
            /** Mode */
            mode: string;
            /** Bar Count */
            bar_count: number;
        };
        /** StorageStats */
        StorageStats: {
            /** Schema Version */
            schema_version: number;
            /** Batches */
            batches: number;
            /** Revisions */
            revisions: number;
            /** Snapshots */
            snapshots: number;
        };
        /** StoredBar */
        StoredBar: {
            /** Revision Id */
            revision_id: string;
            /** Revision */
            revision: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            bar: components["schemas"]["Bar"];
        };
        /** Stream */
        "Stream-Input": {
            /**
             * Source
             * @enum {string}
             */
            source: "fixture" | "binance";
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "BTCUSDT" | "ETHUSDT";
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "5m" | "15m" | "1h" | "4h" | "1d";
            /**
             * Venue
             * @default binance-spot
             * @constant
             */
            venue: "binance-spot";
            /**
             * Market Session
             * @default 24/7
             * @constant
             */
            market_session: "24/7";
            /**
             * Timezone
             * @default UTC
             * @constant
             */
            timezone: "UTC";
            /**
             * Quote Currency
             * @default USDT
             * @constant
             */
            quote_currency: "USDT";
            /**
             * Base Currency
             * @default BTC
             * @enum {string}
             */
            base_currency: "BTC" | "ETH";
            /**
             * Price Encoding
             * @default decimal_string_18_places
             * @constant
             */
            price_encoding: "decimal_string_18_places";
        };
        /** Stream */
        "Stream-Output": {
            /**
             * Source
             * @enum {string}
             */
            source: "fixture" | "binance";
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "BTCUSDT" | "ETHUSDT";
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "5m" | "15m" | "1h" | "4h" | "1d";
            /**
             * Venue
             * @default binance-spot
             * @constant
             */
            venue: "binance-spot";
            /**
             * Market Session
             * @default 24/7
             * @constant
             */
            market_session: "24/7";
            /**
             * Timezone
             * @default UTC
             * @constant
             */
            timezone: "UTC";
            /**
             * Quote Currency
             * @default USDT
             * @constant
             */
            quote_currency: "USDT";
            /**
             * Base Currency
             * @default BTC
             * @enum {string}
             */
            base_currency: "BTC" | "ETH";
            /**
             * Price Encoding
             * @default decimal_string_18_places
             * @constant
             */
            price_encoding: "decimal_string_18_places";
        };
        /** SummaryRisk */
        SummaryRisk: {
            /** Risk9 */
            risk9: string | null;
            /** Risk9 At */
            risk9_at: string | null;
            /** Setup Close */
            setup_close: string | null;
            /** Risk Level */
            risk_level: string | null;
            /** Risk13 At */
            risk13_at: string | null;
            /** Provisional */
            provisional: boolean;
            /** Close13 */
            close13: string | null;
            /** Tdst */
            tdst: string | null;
            next_bar_needs: components["schemas"]["NextBarNeeds"] | null;
        };
        /** SyncJob */
        SyncJob: {
            /** Job Id */
            job_id: string;
            /** Account Id */
            account_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "retry_wait" | "succeeded" | "partial" | "failed";
            /**
             * Phase
             * @enum {string}
             */
            phase: "snapshot" | "fees";
            /** Attempts */
            attempts: number;
            /** Total Orders */
            total_orders: number;
            /** Completed Orders */
            completed_orders: number;
            /** Missing Orders */
            missing_orders: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Next Due
             * Format: date-time
             */
            next_due: string;
            /** Error */
            error: string | null;
        };
        /** SyncRequest */
        SyncRequest: {
            /** Account Id */
            account_id: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /** TimeframeContext */
        TimeframeContext: {
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "5m" | "15m" | "1h" | "4h" | "1d";
            /**
             * Status
             * @enum {string}
             */
            status: "fresh" | "delayed" | "stale" | "unavailable" | "simulated";
            /** Bars Used */
            bars_used: number;
            /** History Complete */
            history_complete: boolean;
            /** History Gapped */
            history_gapped: boolean;
            /** Last Closed At */
            last_closed_at: string | null;
            summary: components["schemas"]["DemarkSummary"] | null;
            state: components["schemas"]["TimeframeState"] | null;
            /** Signals */
            signals: components["schemas"]["Signal"][];
            new_trend: components["schemas"]["NewTrend"] | null;
        };
        /** TimeframeState */
        TimeframeState: {
            /**
             * S9
             * @enum {string}
             */
            s9: "up" | "down" | "none";
            /** S13 */
            s13: boolean;
            /** Carry13 */
            carry13: boolean;
            /** Countdown */
            countdown: number;
            /** Setup9 At */
            setup9_at: string | null;
            /** Qualified13 At */
            qualified13_at: string | null;
            /** Setup9 Seconds Ago */
            setup9_seconds_ago: number | null;
            /** Qualified13 Seconds Ago */
            qualified13_seconds_ago: number | null;
            /** Beyond Risk9 */
            beyond_risk9: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Workspace */
        Workspace: {
            stream: components["schemas"]["Stream-Output"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Current State
             * @enum {string}
             */
            current_state: "fresh" | "delayed" | "stale" | "unavailable" | "simulated";
            snapshot: components["schemas"]["Analysis"] | null;
            latest_job: components["schemas"]["Job"] | null;
            refresh_job: components["schemas"]["Job"] | null;
            schedule: components["schemas"]["Schedule"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_wheelhouse_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    submit_api_wheelhouse_v1_jobs_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_wheelhouse_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_wheelhouse_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_context_api_wheelhouse_v1_market_context_get: {
        parameters: {
            query?: {
                source?: "fixture" | "binance";
                symbol?: string;
                market_at?: string | null;
                knowledge_at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_api_wheelhouse_v1_workspace_get: {
        parameters: {
            query?: {
                source?: "fixture" | "binance";
                symbol?: string;
                timeframe?: "5m" | "15m" | "1h" | "4h" | "1d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_api_wheelhouse_v1_snapshots_get: {
        parameters: {
            query?: {
                source?: "fixture" | "binance";
                symbol?: string;
                timeframe?: "5m" | "15m" | "1h" | "4h" | "1d";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_wheelhouse_v1_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_api_wheelhouse_v1_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_api_wheelhouse_v1_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storage_api_wheelhouse_v1_storage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageStats"];
                };
            };
        };
    };
    connection_api_wheelhouse_v1_portfolio_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    accounts_api_wheelhouse_v1_portfolio_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    discover_api_wheelhouse_v1_portfolio_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    sync_api_wheelhouse_v1_portfolio_sync_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_job_api_wheelhouse_v1_portfolio_sync_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_wheelhouse_v1_portfolio_sync_status_get: {
        parameters: {
            query: {
                account_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJob"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_api_wheelhouse_v1_portfolio_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    workspace_api_wheelhouse_v1_portfolio_workspace_get: {
        parameters: {
            query: {
                source: "demo" | "moomoo";
                account_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cycle_api_wheelhouse_v1_portfolio_cycles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCycle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cycle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_api_wheelhouse_v1_portfolio_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LedgerEvent-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotation_api_wheelhouse_v1_portfolio_annotations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Annotation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fee_correction_api_wheelhouse_v1_portfolio_fee_corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeeCorrection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_api_wheelhouse_v1_portfolio_reconcile_fill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FillReconciliation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
